### ISSUE TITLE
Heads up on UX updates for your event this week

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/seattle#5]
@jimcal @frijol @zebul Just wanted to make sure you've seen a few very recent UX updates so you're not surprised in the middle of your big event this week. 

- There's now a landing page for each tutorial, which will make it easy to create links to a table of contents for each 
- Users can now click to view the solution to any lesson 
- There's now some logging to the console instead of making the users open up the terminal, as in [blog lesson 2](https://proto.school/#/blog/02)
- There are now social cards when you share our URL on Twitter and such

I'm sure I'm forgetting plenty, but these are the ones that come to mind. Hope some of this new functionality is helpful. 

Please encourage your attendees to use those buttons at the bottom of the page to report bugs or suggest improvements. I look forward to hearing how it goes!

**Comment by jimcal** [comment]
Thanks for the heads up! Will share feedback and lesson learns back to the community!

**Comment by jimcal** [comment]
Closing this issue as the first meetup has concluded. Worth mentioned at least one issue was addressed and merged ([#211](https://github.com/ProtoSchool/protoschool.github.io/issues/211)).
